### ISSUE TITLE
Typo in Repository README

### ISSUE THREAD

**Issue by MrFlynn** [komuw/sewer#111]
## What is it that you would like to propose to add/remove/change?
There is a typo in the code in the repository README, specifically in the "Bring Your Own DNS Provider" section. The proper `Name` attribute for the AWS Route53 ResourceRecordSet should be:
```python
'ResourceRecordSet': {
    'Name': '_acme-challenge' + '.' + domain_name, # No trailing period.
    # More attributes here...
}
```

and not:
```python
'ResourceRecordSet': {
    'Name': '_acme-challenge' + '.' + domain_name + '.', # Trailing period is incorrect.
    # More attributes here...
}
```

(the above is directly from the README).

## Why do you want to add/remove/change that?
Using the code verbatim from the README causes the validation step to fail with the ACME service. The trailing period is inserted by Route53 automatically, so it doesn't need to be handled by the client.

The primary reason to change this is just to ensure that the example provided for creating your own DNS provider is correct and works as intended.

**Comment by komuw** [comment]
@MrFlynn Hi.

Are you sure about that?
Other route53 letsencrypt clients have '.' at the end: https://github.com/jed/certbot-route53/blob/fc605faae2d2e7acd87604aa9e699d7f407a6a97/certbot-route53.sh#L53

**Comment by MrFlynn** [comment]
When I tested the code, the ACME services returns the following error: `Error: Bad Request: { "type": "urn:ietf:params:acme:error:malformed", "detail": "Order's status (\"invalid\") is not acceptable for finalization", "status": 400 }`. Removing the trailing period allows ACME to validate the challenge.

Regardless, the [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/route53.html#Route53.Client.change_resource_record_sets) (scroll down to ResourceRecordSet) specify that the `Name` parameter is treated identically regardless if it has a trailing period or not. It's possible that there is a bug in boto3 or botocore that makes this statement false, but I haven't been able to find it.

**Comment by MrFlynn** [comment]
Additionally, another typo I found is that the ResourceRecord value should be quoted:
```python
'ResourceRecords': [{
    'Value': '"{0}"'.format(domain_dns_value),
}]
```

Quoting the TXT record value conforms with the [AWS developer guide](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#TXTFormat). Additionally, omitting those quotes causes boto3 to raise a validation error.

**Comment by mmaney** [comment]
I would suggest replacing a long, probably somewhat annotated copy of an existing dns_provider module with a more abstract skeleton... but one which includes the important details, like **not** importing a provider-specific library at the module level, and documenting the various places you have to edit to integrate a new provider module into (I guess that's mostly to get it to work with cli.py, although the sewer-as-lib examples show importing sewer.ThisProviderDns, so anyone who follows that example needs some of this, too).

**Comment by komuw** [comment]
@mmaney I think that would be a good alternative

**Comment by mmaney** [comment]
And lo, it finally came to pass that the example has been rewritten, removing all that obfuscating detail specific to one particular service provider as well as adopting the new-model interface.
