### ISSUE TITLE
Missing sleep after dns record creation

### ISSUE THREAD

**Issue by fpgaminer** [komuw/sewer#115]
## Which version of python are you using?
3.7
## What operating system and version of operating system are you uing?
MacOS
## What version of sewer are you using?
0.7.0
## What did you do? (be as detailed as you can)
    client = sewer.Client(domain_name=domain, dns_class=dns_class, ACME_DIRECTORY_URL=sewer.config.ACME_DIRECTORY_URL_STAGING, account_key=account_key, LOG_LEVEL="DEBUG")
    print("CERT: ", client.cert())
## What did you expect to see/happen/not happen?
A certificate issued
## What did you actually see/happen? 
Let's Encrypt said the challenge was invalid.

## Truncated log:

```
create_dns_record_end
check_authorization_status
...'status': 'pending'...
check_authorization_status_success
respond_to_challenge
make_signed_acme_request
get_acme_header
get_nonce
sign_message
respond_to_challenge_success
check_authorization_status
...'status': 'invalid'...
```

## Notes
Sewer creates the DNS record successfully, but Let's Encrypt says it's invalid.  This happens on both Staging and Production.  `acme.sh` works with the same setup.  I checked `acme.sh`'s implementation and they have a 20 second sleep after DNS record creation.  So I added a sleep to Sewer after it calls `create_dns_record` and now it works successfully.

Link to `acme.sh`'s relevant code: https://github.com/Neilpang/acme.sh/blob/02882fb327002f826ce105cb6f593b1860d780ef/acme.sh#L4007

**Comment by Tungsteno74** [comment]
Hi @fpgaminer ,

Can you create a fork with this fix, please?

**Comment by hbradleyiii** [comment]
I am having the same problem. The acme.sh script works fine assuming I have a delay of at least 60 seconds. I have done a delay of 30 minute (2000 seconds) with sewer and it still doesn't work -- unless I add a sleep (of at least 60 seconds in my case) after create_dns_record. I kept thinking that maybe I was doing something wrong, but I'm consistently getting the same result.

**Comment by hbradleyiii** [comment]
I have a pull request for a suggested fix here: https://github.com/komuw/sewer/pull/121
