### ISSUE TITLE
Cloudflare token support

### ISSUE THREAD

**Issue by moritz89** [komuw/sewer#127]
## What is it that you would like to propose to add/remove/change?
I would like to add support for using Cloudflare DNS with tokens instead of only relying on email + API key authentication.

## Why do you want to add/remove/change that?
Tokens allow restricting which API functionality can be accessed. This is useful to minimize potential damage due to stolen keys and accidentally changing / deleting important settings.

## How do you want to go about adding/removing/changing that?
- Replace the header with "Authorization: Bearer token-xx-here" instead of "X-Auth"
- Either use a separate DNS class or extend the init signature of the Cloudflare DNS class and the CLI

**Comment by komuw** [comment]
hi @moritz89 

This sounds reasonable. 

> Either use a separate DNS class or extend the init signature of the Cloudflare DNS class and the CLI

If we can keep one Cloudflare Dns class and still support tokens, that would be prefferable

**Comment by komuw** [comment]
accepted, pull requests are welcome
