### ISSUE TITLE
Cloudflare TXT record is not removed

### ISSUE THREAD

**Issue by cyb3rwr3ck** [komuw/sewer#134]
## Which version of python are you using?
3.8

## What operating system and version of operating system are you using?
Debian 10.2

## What version of sewer are you using?
0.7.9

## What did you do? (be as detailed as you can)
Creating wildcard certificates for a sub domain a cloudflare (*.sub.example.com)

## What did you expect to see/happen/not happen?
After the successful creation of the certificates the TXT records should be removed.  

## What did you actually see/happen? 
_acme-challenge.sub TXT record remains

## Paste here the log output generated by `sewer`, if any. Please remember to remove any sensitive items from the log before pasting here.
```
intialise_success, sewer_version=0.7.9, domain_names=['*.[SNIP]'], acme_server=https://acme-v02.api...
acme_register
acme_register_success
apply_for_cert_issuance
apply_for_cert_issuance_success
get_identifier_authorization
get_identifier_authorization_success
create_dns_record
create_dns_record_end
check_authorization_status
check_authorization_status_success
check_authorization_status
check_authorization_status_success
send_csr
send_csr_success
download_certificate
download_certificate_success
delete_dns_record
delete_dns_record_success
```

**Comment by mmaney** [comment]
I don't use cloudflare, but it looks obvious.  In create_dns_record this is near the start:

        # if we have been given a wildcard name, strip wildcard
        domain_name = domain_name.lstrip("*.")
        ....           
        "name": "_acme-challenge" + "." + domain_name + "."

And this name is what's used in the API request.  In delete_dns_record there is no lstrip and it appears to use the domain name as it was passed in (so with the leading '*.') in that API call.  The code that sets up for the removal API call forms the name like this:

        dns_name = "_acme-challenge" + "." + domain_name
        list_dns_payload = {"type": "TXT", "name": dns_name}

Which it seems to me is most unlikely to have the desired result.  Again, I don't use cloudflare, and have no way to test this, but I would be surprised if adding a copy of that lstrip line from the create method to the remove method wouldn't fix this right up.

**Comment by komuw** [comment]
@cyb3rwr3ck I have applied the fix suggested by @mmaney . 

Can you try out https://pypi.org/project/sewer/0.8.1b1/ and let me know if it fixes this issue
