### ISSUE TITLE
Missing HTTP Provider

### ISSUE THREAD

**Issue by BuddhaOhneHals** [komuw/sewer#181]
Hi,

I'm trying to create a custom HTTP provider like it's described in the README. But there seems to be no `sewer.BaseHttp` or any other class providing such functionality.

Have you removed the possibility to use an HTTP challenge? Are you planning to re-implement this feature?

Best,
Timo

**Comment by BuddhaOhneHals** [comment]
I'm sorry, just stumbled upon https://github.com/komuw/sewer/blob/master/docs/UnifiedProvider.md. I assume the README is outdated.

**Comment by mmaney** [comment]
Yes, the provider stuff has changed.  The stuff in the docs directory is the most up to date, and a lot of the README needs to be... well, a lot of it should be shoved off into separate docs files as well as revised.  Just ran out of steam and am hoping komuw can push ti out to PyPi soon so I can go further out on a limb without having to worry about folks being forced to chase master for things like the updated protocol.

Anyway, for you providers/demo.py has a sort of working new-model driver.  Very, very simple, and without a prompt to wait for "okay, I did that" it's not actually useful, but that was a feature when I was using it to test things <wink>.

I look forward to seeing a real HTTP challenge provider, Timo!
