### ISSUE TITLE
Docs on renew are in conflict.

### ISSUE THREAD

**Issue by tinpotnick** [komuw/sewer#194]
Alternatively if you want to conribute to this repo, answer this questions instead in your issue:                    

## What is it that you would like to propose to add/remove/change?

On the main readme it gives a usage example of:

with open('account_key.key', 'r') as account_key_file:
    account_key = account_key_file.read()

client = sewer.client.Client(
    domain_name='example.com',
    dns_class=dns_class,
    account_key=account_key
)
certificate = client.renew()

But in sewer/client.py it has the following comments:

        :param account_key:                  (optional) [string]
            a string whose contents is an ssl certificate that identifies your account on the acme server.
            if you do not provide one, this client will issue a new certificate else will renew.
        :param certificate_key:              (optional) [string]
            a string whose contents is a private key that will be incorporated into your new certificate.
            if you do not provide one, this client will issue a new certificate else will renew.

certificate_key is not set in your example for renew.

## Why do you want to add/remove/change that?

My understanding is you need to provide certificate_key - but I am not 100% sure. This makes it a little ambiguous.

## How do you want to go about adding/removing/changing that?

Update the either the main page or the comments in client.py. I suspect the main readme requires updating. My understanding is on a renew the certificate_key (private key?) shouldn't renew or change (but I don't spend much time on certificates...).

**Comment by mmaney** [comment]
Yes, the docs have needed a good reworking for a while.  Some of that has been begun, and partial results can be found in /docs.  There's more, including a good deal of outright replacement of some of the vintage sections of the README, still in progress.

NB: the new /docs sometimes apply to post-0.8.2.  They should be in sync with the unreleased code in the repo, which will become 0.8.3 RealSoonNow... for some summertime value of soon, alas.

You are correct that the current handling of both the account key (which IS the account to ACME) and the server certificate keys is a bit muddy, and some things that ought to be simple are ... let's say cumbersome, shall we?  The [sewer-cli docs](https://github.com/komuw/sewer/blob/master/docs/sewer-cli.md) talk about that a little bit.  In the somewhat longer run there will be more incompatible changes to address these things.

**Comment by mmaney** [comment]
Clarification, as much as I have on tap for now:

Neither the account key nor the certificate key NEED be provided.  There are reasons to prefer passing them in over letting sewer create new keys for one or both, but that has more to do with local policy than ACME requirements.  I would guess that if you don't know very well why you wish to reuse one or both of these, you're likely just as well off not.
