### ISSUE TITLE
Issue's adding dns provider for Aurora DNS (Apache Libcloud)

### ISSUE THREAD

**Issue by wilfriedjonker** [komuW/sewer#33]
## Which version of python are you using?
Python 2.7.12
## What operating system and version of operating system are you uing?
Ubuntu 16.04
## What version of sewer are you using?
0.2.4
## What did you do? (be as detailed as you can)
Adding aurora DNS provider

## What did you expect to see/happen/not happen?
Getting a certificate, but got a error. Sees attachement for full output 

## What did you actually see/happen? 
I think some specific information is expected form the function create_dns_record and delete_dns_record. But it is not clear to me what this is en in what format it is expected. 

## Paste here the log output generated by `sewer`, if any. Please remember to remove any sensitive items from the log before pasting here.                                           
see output.log

See also aurora.txt  to see code from the provider.
[aurora.txt](https://github.com/komuW/sewer/files/1162730/aurora.txt)
[output.txt](https://github.com/komuW/sewer/files/1162715/output.txt)

**Comment by komuW** [comment]
@wilfriedjonker 
Hello, sorry about that.

As you can see from[1]; `The only currently supported DNS provider is cloudflare but I will add more as time progresses`. 

Having said that, I think I know why you got the failure/bug. I'll work to fix that and ping you when it is fixed. Do you by any chance know if Aurora DNS have a free tier/plan that I can use to test the integration?
Thanks for filing the bug report.


references:
1. https://github.com/komuW/sewer/blob/master/README.md

**Comment by wilfriedjonker** [comment]
Using aurora is woudl be free for the purpose of testing (https://www.pcextreme.com/aurora/dns). There are some cost's for registering a domain.

**Comment by komuW** [comment]
@wilfriedjonker Hi,

I was unable to get an account for aurora DNS, but I'll continue working towards one.

I have however, put out a fix that I think will address the issue you experienced. The fix went out in this PR: https://github.com/komuW/sewer/pull/35 
If you install this new minor version: https://pypi.python.org/pypi/sewer/0.2.4.1 or pull the new HEAD of master, then you should be able to try it out.

Let me know if this fixes the issue for you.

**Comment by wilfriedjonker** [comment]
@komuW now it works :).

**Comment by komuW** [comment]
closed by: https://github.com/komuW/sewer/pull/38
