### ISSUE TITLE
Add a distinct User-Agent header to Sewer's ACME requests

### ISSUE THREAD

**Issue by cpu** [komuW/sewer#4]
Hi there, thanks for all of your work on this client! :tada:

Occasionally Let's Encrypt bumps into problems with requests from specific ACME clients. When that happens, it's much easier to diagnose if the client sends a distinct user-agent following the recommendations from the ACME spec.

[Section 6.1 of ACME Draft-07](https://tools.ietf.org/html/draft-ietf-acme-acme-07) has this "SHOULD" recommendation for clients that would be a good starting point:

> ACME clients SHOULD send a User-Agent header in accordance with [RFC7231], including the name and version of the ACME software in addition to the name and version of the underlying HTTP client
software.

Would you be willing to add a UA header to Sewer? Thanks so much!

**Comment by komuW** [comment]
Hi @cpu 
Thanks for bringing that up. 
I'll definitely do that. 

:cherries:

**Comment by komuW** [comment]
closed by https://github.com/komuW/sewer/pull/6
