### ISSUE TITLE
Missing attribute in Cryptography library when attempting to create cert

### ISSUE THREAD

**Issue by vanpelt** [komuW/sewer#66]
## Which version of python are you using?

2.7.13

## What operating system and version of operating system are you uing?

Mac 10.13.1

## What version of sewer are you using?

Latest

## What did you do? (be as detailed as you can)

Tried to create a certificate with an existing account key

## What did you expect to see/happen/not happen?

To get a cert

## What did you actually see/happen? 

Got an exception

## Paste here the log output generated by `sewer`, if any. Please remember to remove any sensitive items from the log before pasting here.

```
    221         # private key public exponent in hex format
--> 222         exponent = "{0:x}".format(public_key_public_numbers.e)
    223         exponent = "0{0}".format(exponent) if len(exponent) % 2 else exponent
    224         # private key modulus in hex format

AttributeError: 'EllipticCurvePublicNumbers' object has no attribute 'e'
```       

Looked at previous versions of the cryptography library and couldn't find any with an "e" attribute.  Any idea's where this came from?  I'm using cryptography 2.1.3

**Comment by komuW** [comment]
Hi @vanpelt 

I just tried the following program using cryptography 2.1.3 and it worked.
```python
import cryptography
import OpenSSL

key_type=OpenSSL.crypto.TYPE_RSA
key = OpenSSL.crypto.PKey()
key.generate_key(key_type, 2048)
p_key = OpenSSL.crypto.dump_privatekey( OpenSSL.crypto.FILETYPE_PEM, key)

private_key = cryptography.hazmat.primitives.serialization.load_pem_private_key(p_key, 
password=None, 
backend=cryptography.hazmat.backends.default_backend()
)
public_key_public_numbers = private_key.public_key().public_numbers()
exponent = public_key_public_numbers.e
modulus = public_key_public_numbers.n
print exponent
print modulus
```
The account key you used, was it one that was created by sewer or was it created by some other program?

**Comment by komuW** [comment]
closing for now, please re-open if you run into this again or if more information becomes available
