### ISSUE TITLE
Order of identifiers in apply_for_cert_issuance_response from server is not retained

### ISSUE THREAD

**Issue by dsp05** [komuw/sewer#86]
https://github.com/komuw/sewer/blob/ef4e31c6e8e864c41bebe2db42d595d18b1290d5/sewer/client.py#L334

This will fail for multiple domains

**Comment by komuw** [comment]
Hi, thanks for opening this. 
I do believe it is a duplicate of https://github.com/komuw/sewer/issues/83 

I have a pull request open to try and fix this; https://github.com/komuw/sewer/pull/84 
That pull request is work in progress; but it should be ready to merge in a few days.
