### ISSUE TITLE
Get intermediate certificate

### ISSUE THREAD

**Issue by J88G** [komuw/sewer#97]
Hi
Can you please inform me how can I get the:

- intermediate certificate
- chain certificate

Also, why when the result of `certificate = self.download_certificate(certificate_url)` are 2 certificates? Can you help me to identify each one? 

Thank you very much

**Comment by komuw** [comment]
@J88G 

`client.cert()` will download the certificate together with the chain
`client.certificate_key` will give you the client certificate
`client.account_key` will give you the account key
`client.csr` will give you the certificate signing request

when you get the certificate+chain using `client.cert()` , you can use `openssl` as an example to get the intermediate and chain.

`openssl x509 -in some_certificate_and_chain.crt -text -noout`

**Comment by J88G** [comment]
@komuw 
Great , thank you very much.
